### ISSUE TITLE
ServiceWorker registration isn't working in a reliable fashion

### ISSUE THREAD

**Issue by peppsac** [Phoxygen/sw_fm#15]
The navigator.serviceWorker.register(url) call made registerServiceWorker sometimes fails to return anything, which blocks app initialisation (due to chained .then()).

Francisco suggested to avoid registering the SW everytime, but instead only register if not only registered (see https://github.com/arcturus/serviceworker-claim/blob/master/index.html#L17-L21 )

**Comment by peppsac** [comment]
Regardless of the suggested improvment, the root issue is still present: the call to navigator.serviceWorker.register doesn't always callback the onsuccess or onerror method.

**Comment by peppsac** [comment]
After adding a few logs to sw.js, utils.js and worker_api.js, we can observe the different behaviors.
Using this test scenario:
- unregister ServiceWorker in settings
- start application
- see what happened in the logs

Here's an example of the register() call succeeding:

```
I/SW FM Radio( 7179): Content JS LOG: [startup]  ServiceWorker not registered yet
I/SW FM Radio( 7179):     at debug (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/views/main/js/startup.js:21:5)
I/SW FM Radio( 7179): Content JS LOG: [startup]  navigator.serviceWorker.register(../../../app/sw.js)
I/SW FM Radio( 7179):     at debug (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/views/main/js/startup.js:21:5)
I/SW FM Radio( 7179): Content JS LOG: BEFORE import scripts
I/SW FM Radio( 7179):     at <anonymous> (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/sw.js:5:1)
I/SW FM Radio( 7179): Content JS LOG: UTILS.js
I/SW FM Radio( 7179):     at <anonymous> (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/js/sw/utils.js:3:1)
I/SW FM Radio( 7179): Content JS LOG: WORKER_API.js
I/SW FM Radio( 7179):     at <anonymous> (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/js/sw/rendercache/worker_api.js:3:1)
I/SW FM Radio( 7179): Content JS LOG: UTILS.js
I/SW FM Radio( 7179):     at <anonymous> (js/sw/utils.js:3:1)
[truncated]
```

Here's an example of a failed launch:

```
I/SW FM Radio( 5528): Content JS LOG: [startup]  ServiceWorker not registered yet
I/SW FM Radio( 5528):     at debug (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/views/main/js/startup.js:21:5)
I/SW FM Radio( 5528): Content JS LOG: [startup]  navigator.serviceWorker.register(../../../app/sw.js)
I/SW FM Radio( 5528):     at debug (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/views/main/js/startup.js:21:5)
E/Smart Collections( 5325): Content JS ERROR: evme ERROR NativeInfo error  
E/Smart Collections( 5325):     at error (app://collection.gaiamobile.org/gaia_build_defer_synchronize.js:476:845)
E/Smart Collections( 5325):     at onerror (app://collection.gaiamobile.org/gaia_build_defer_synchronize.js:541:734)
E/Smart Collections( 5325): Content JS ERROR: evme ERROR NativeInfo error  
E/Smart Collections( 5325):     at error (app://collection.gaiamobile.org/gaia_build_defer_synchronize.js:476:845)
E/Smart Collections( 5325):     at onerror (app://collection.gaiamobile.org/gaia_build_defer_synchronize.js:541:734)
E/Smart Collections( 5325): Content JS ERROR: evme ERROR NativeInfo error  
E/Smart Collections( 5325):     at error (app://collection.gaiamobile.org/gaia_build_defer_synchronize.js:476:845)
E/Smart Collections( 5325):     at onerror (app://collection.gaiamobile.org/gaia_build_defer_synchronize.js:541:734)
I/SW FM Radio( 5528): Content JS LOG: BEFORE import scripts
I/SW FM Radio( 5528):     at <anonymous> (app://b0501643-d13d-479d-8cd9-9d2ea94754aa/app/sw.js:5:1)
```

Note that in the failure case the log is not truncated: this is really the last line in logcat related to the sw.js script.
